VPN / OpenVPN / Client Export - return empty list when /api/openvpn/export/accounts/ is called without parameters.
found some of these in the crash reports:  ArgumentCountError: Too few arguments to function OPNsense\OpenVPN\Api\ExportController::accountsAction(), 0 passed and exactly 1 expected in /usr/local/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ExportController.php:204

(cherry picked from commit be8a6cd51420d1b3d7ffe893975a99913b81fbb5)