captive portal: adjust ARP logic to ISO format per https://github.com/opnsense/core/commit/4b86d4e638b7968158a4691e511e174ca927ed13
ValueError: time data '2026-06-29T12:34:19Z' does not match format '%Y-%m-%d %H:%M:%S'
(cherry picked from commit 1f1612aa1024c343711a6ad8c20ca39e08e6645e)