Reporting: Traffic - fix netaddr incompatibility (AttributeError: 'IPAddress' object has no attribute 'is_private')
(cherry picked from commit 0d7b9fd34f4aa92eb5503d1cd7d843b87643d7a4)