HTML Compliance - Attribute "type" on Element <i>
Error: Attribute "type" not allowed on element <i> at this point.
(cherry picked from commit b2f4cfa7c1362eebf251d9f938ba25af3a04aea9)