gateways: null is not going to be a UUID either
ErrorException: Using null as an array offset is deprecated, use an empty string instead in /usr/local/opnsense/mvc/app/controllers/OPNsense/Routing/Api/SettingsController.php:162
Stack trace:

(cherry picked from commit d7cc8e1c0f10f26d0696e74f6127eecea42b672e)