Firewall: Diagnostics: Aliases - fix AttributeError: 'DNAME' object has no attribute 'address' on fetch
(cherry picked from commit 496fa66447fec7d726365bf6e6972510ef2ae746)