Lobby: Dashboard - add a safety fence in productInfoFeedAction() in case the firewall has no intrenet access.
Fixes:

Error: Call to a member function children() on null in /usr/local/opnsense/mvc/app/controllers/OPNsense/Core/Api/DashboardController.php:201
Stack trace:

(cherry picked from commit 822df6cc6909c776e3207ac5cb2578f5ad883e9a)