interfaces: move migration prefix for new settings
Error: Call to a member function applyDefault() on null

(from the Bridge model)

(cherry picked from commit b439e6484f96ecd9e91bf56f5d19307333bc2982)