HTML Compliance - Lobby: Dashboard Widgets (#2082)
Error: Attribute alt not allowed on element span at this point.

Error: Table columns in range 2…4 established by element td have no cells beginning in them.

Error: Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
Error: Row 1 of a row group established by a tbody element has no cells beginning on it.
Warning: A table row was 0 columns wide, which is less than the column count established by the first row (5).

Error: Duplicate ID submita.
Error: Bad value 100% for attribute width on element img: Expected a digit but saw % instead.
Error: Bad value 100% for attribute height on element img: Expected a digit but saw % instead.
Warning: The border attribute is obsolete. Consider specifying img { border: 0; } in CSS instead.

Avoid potential future Error: Duplicate ID submit.
Error: Attribute autocomplete is only allowed when the input type is color, date, datetime-local, email, hidden, month, number, password, range, search, tel, text, time, url, or week.

(cherry picked from commit d944d0d2ff26ff757bc47b5ab6d4f29fc1f56fce)