logging: ignore TypeErrors as well when parsing log lines, fixes:
Traceback (most recent call last):
  File "/usr/local/opnsense/scripts/syslog/queryLog.py", line 63, in <module>
    for record in log_matcher.match_records(valid_from):
  File "/usr/local/opnsense/scripts/syslog/log_matcher.py", line 100, in match_records
    if timestamp and isoparse(record['timestamp']).timestamp() < timestamp:
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/isoparser.py", line 37, in func
    return f(self, str_in, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/isoparser.py", line 134, in isoparse
    components, pos = self._parse_isodate(dt_str)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/isoparser.py", line 208, in _parse_isodate
    return self._parse_isodate_common(dt_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/isoparser.py", line 213, in _parse_isodate_common
    len_str = len(dt_str)
              ^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

(cherry picked from commit 1a3744fc606ee8af4253f607cf14636fee60dd95)